### ISSUE TITLE
Unable to Compile - "bash: make: command not found"

### ISSUE THREAD

**Issue by GlacialPillow** [VitaSmith/cdecrypt#10]
Compiling on Steam Deck fails with this message. The cdecrypt folder is downloaded. When using the cdecrypt command, it returns "bash: cdecrypt: command not found". I tried again after following pineguy-64's comment on JSaterdalen's [issue](https://github.com/VitaSmith/cdecrypt/issues/6) but nothing seems to change. I'm new to this so I might just be doing it wrong but I'd appreciate any help.

**Comment by eacpereira** [comment]
I'm not certain from your comment you're actually compiling the code, since you seem to just be trying to run the command `cdecrypt` without doing anything else. Your initial step after downloading (and extracting, if needed) the folder should be to `cd` into the folder and use the command `make ./Makefile`. This will create a file just called `cdecrypt`, which you can then use as a command by copy-and-pasting its path. For instance, if `cdecrypt` is in `/home/deck/Downloads/cdecrypt_folder` and the NUS file is `/home/deck/ROMS/BOTW.NUS` you would use the following command, where `~` is a shortcut to the current user's home folder:

`~/Downloads/cdecrypt_folder/cdecrypt ~/ROMS/BOTW.NUS`

**Comment by VitaSmith** [comment]
I'm going to consider this issue closed, as cdecrypt should compile just fine on a Linux environment where a GNU toolchain has been installed.
